language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "4.3"
before_script:
  - npm install grunt-cli -g
script:
  - grunt build
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
