language: node_js
node_js:
  - "0.10.40"
before_script:
  - npm install grunt-cli -g
after_success:
  - cat /home/travis/build/dominicrico/db-convert/coverage/lcov.info | /home/travis/build/dominicrico/db-convert/node_modules/coveralls/bin/coveralls.js
